global-rate-limit:
  time_unit: minute
  time_interval: 1
  max_requests: 60
  identification_methods:
    - IP

routes:
  - path: /hi
    target_host: https://www.google.com 
    target_path: /
    strip_path: true